# frozen_string_literal: true

source 'https://rubygems.org'
ruby '~> 2.4.1'

gem 'bundle'
gem 'erubi'
gem 'haml'
gem 'inflecto'
gem 'omniauth-google-oauth2'
gem 'pry'
gem 'puma'
gem 'rack-unreloader'
gem 'rack_csrf'
gem 'rake'
gem 'roda'
gem 'sass'
gem 'selenium-webdriver'
gem 'sequel'
gem 'sequel_pg'
gem 'tilt', '>= 2'

gem 'capybara'
gem 'minitest', '>= 5.7.0'
gem 'minitest-hooks', '>= 1.1.0'
